# Generated by Django 4.0.4 on 2022-06-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='point',
        ),
    ]
